### ISSUE TITLE
Design micro-optimization strategies

### ISSUE THREAD

**Issue by DanielOsorio01** [ISIS3510-202320-Team22/Flutter#64]
“Since you have to show the implementation of micro optimization, you have to show your
code and the results on the profiling tool before implementing the micro-optimization, then
you have to show also snippets of code for the implementation and also the results of the
profiling tool.“

**Comment by xavi-serrano** [comment]
Micro-optimizations done https://github.com/ISIS3510-202320-Team22/Flutter/pull/80
